version: '3'
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ~/slb_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  liquibase:
    image: liquibase/liquibase:4.30.0
    container_name: liquibase
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_CHANGELOG_FILE: /changelog/test_table.yaml
      LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=public
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: postgres
      LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: public
      LIQUIBASE_SEARCH_PATH: /liquibase
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    command: --defaults-file=/liquibase/changelog/liquibase.properties update
  slb:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: slb
    ports:
      - "8080:8080"
    depends_on:
      liquibase:
        condition: service_completed_successfully
